rules:
    indentation:
        - 2
        - size: 4

    quotes:
        - 2
        - style: single

    zero-unit:
        - 1
        - include: false

    property-sort-order:
        - 0
        - ignore-custom-properties: false

    no-color-literals:
        - 0

    class-name-format:
        - 1
        - convention: hyphenatedbem

    force-pseudo-nesting:
        - 0

    nesting-depth:
        - 1
        - max-depth: 4
